[package]
name = "rustlang-base"
version = "0.1.0"
edition = "2024"

[dependencies]


[workspace]
members = ["base-learn","chat", "command","csv-ops", "echo-server", "tokio_intro"]
default-members = ["command"]
